version: '3'

services:
  db:
    image: mysql:5.7
    ports:
      - '3306:3306'
    environment:
       MYSQL_DATABASE: 'insurance'
       MYSQL_USER: 'root'
       MYSQL_PASSWORD: 'secret'
       MYSQL_ROOT_PASSWORD: 'secret'
    volumes:
      - my-db:/var/lib/mysql
  backend:
    build: ./insurance_backend
    command: run.sh #python manage.py runserver 0.0.0.0:8000
    entrypoint: /insurance_backend/entrypoint.sh
    volumes:
      - .:/Insurance/insurance_backend
    ports:
      - "8000:8000"
    depends_on:
      - db
  frontend:
    build: ./insurance_frontend
    ports:
      - 8080:8080
    command: sh -c "npm install && npm run serve"
    volumes:
      - .:/Insurance/insurance_frontend
    environment:
      HOST: 0.0.0.0
    depends_on:
      - db
volumes:
  my-db: