# Generated by Django 2.2.1 on 2019-05-22 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('risk_types', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('risk_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk', to='risk_types.RiskType')),
            ],
        ),
        migrations.CreateModel(
            name='RiskInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=255)),
                ('risk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risks.Risk')),
                ('risk_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_input', to='risk_types.RiskField')),
            ],
        ),
    ]
